---
title: "care_provider"
format: html
editor: visual
---

```{r}
source("load_defaults.R")
```

## Formal Hours

```{r}
# Load asec formal care activities
asec <- readRDS("../../02_data-prep-and-cleaning/03_ASECdata.rds") |>
  filter(YEAR == max(YEAR)) |>  
  filter(AGE >= 18) |> 
  select(YEAR, OCC2010, empstat, occ_label, UHRSWORKT, EARNWT, INCWAGE, 
         occ_care_focus, ASECWT, sex, gender_parent) |> 
  clean_names() 
  

# create columns required by the app
cp_formal <- asec |> 
  filter(empstat == "Employed") |>
  mutate(
    gender = str_to_lower(sex), 
    provider_status = case_when(
      gender_parent %in% c("Mothers", "Fathers") ~ "with_children",
      gender_parent %in% c("Non-Mothers", "Non-Fathers") ~ "without_children",
      TRUE ~ "other"
    ), 
    time_use = ifelse(occ_care_focus == "none", "non_care", "care"),
    care_focus = occ_care_focus,
    care_type	= "formal", 
    provider_attention = "active"
  ) 

# summarise formal stats
cp_formal <- cp_formal %>%
  filter(uhrsworkt != 997) |> 
  mutate(uhrsworkt = ifelse(uhrsworkt == 999, 0, uhrsworkt)) |> 
  summarise(
    population = sum(asecwt),
    provision_interval = sum(uhrsworkt/7*60*asecwt), 
    .by = c(gender, provider_status, time_use, care_type, 
            care_focus, provider_attention)
  )
```

## Informal Hours

```{r}
# load data
atus <- readRDS("../../02_data-prep-and-cleaning/03_ATUSdata.rds") |> 
  filter(activity != "Formal Work") |> 
  filter(AGE >= 18) |>
  filter(YEAR >= 2018 & YEAR != 2020) |> 
  select(YEAR, CASEID, WT06, sex, gender_parent, act_care_focus, 
         DURATION, SCC_ALL_LN, SEC_ALL_LN) |> 
  clean_names() 

# get most recent 5 year and clean up columns
yr_range <- atus_yr_range(atus) |> 
  filter(year == max(year))

# prep secondary care time
cp_informal <- atus |> 
  pivot_longer(
    cols = c(duration, scc_all_ln, sec_all_ln), 
    names_to = "metric", 
    values_to = "duration"
  ) |> 
  filter(!is.na(duration)) 

# create columns required by the app
cp_informal <- cp_informal |> 
  mutate(
    gender = str_to_lower(sex), 
    provider_status = case_when(
      gender_parent %in% c("Mothers", "Fathers") ~ "with_children",
      TRUE ~ "without_children"
    ), 
    care_type	= "informal", 
    provider_attention = case_when(
      metric == "scc_all_ln" ~ "passive_child", 
      metric == "sec_all_ln" ~ "passive_elder",
      TRUE ~ "active"
      ), 
    care_focus = case_when(
      metric == "scc_all_ln" ~ "developmental", 
      metric == "sec_all_ln" ~ "health",
      act_care_focus == "non-care" ~ "none", 
      TRUE ~ act_care_focus
      ), 
    time_use = ifelse(care_focus == "none", "non_care", "care"),
    weight = wt06/365
  ) 

# summarise formal stats
cp_informal <- cp_informal |> 
  summarise(
    total_time = sum(duration), 
    .by = c(year, caseid, weight, gender, provider_status, time_use, 
            care_type, care_focus, provider_attention)
    ) |> 
  summarise(
    provision_interval = sum(total_time*weight/5),
    population = sum(weight/5), 
    .by = c(gender, provider_status, time_use, 
           care_type, care_focus, provider_attention)
  )
```

## Output Required Files

```{r}
cp_combined <- bind_rows(
  cp_formal, 
  cp_informal
) |> 
  arrange(care_type, time_use, gender, provider_status, care_focus)

write.csv(cp_combined, "./app_data/care_provider_datum.csv", 
          row.names = FALSE)
```

```{r}
cp_population <- asec |> 
  mutate(
    gender = str_to_lower(sex), 
    provider_status = case_when(
      gender_parent %in% c("Mothers", "Fathers") ~ "with_children",
      gender_parent %in% c("Non-Mothers", "Non-Fathers") ~ "without_children",
      TRUE ~ "other")
    )|> 
  summarise(population = sum(asecwt), .by = c(gender, provider_status)) |> 
  arrange(gender, provider_status)
  
write.csv(cp_population, "./app_data/care_provider_population.csv", 
          row.names = FALSE)
```
